version: '3'

services:
  nandu:
    image: ghcr.io/taskforcesh/nandu:latest
    restart: always
    ports:
      - "${NANDU_PORT:-4567}:4567"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database configuration
      NANDU_SEQUELIZE_URI: ${NANDU_SEQUELIZE_URI:-postgres://nandu:nandu@postgres:5432/nandu}
      # JWT configuration
      NANDU_JWT_SECRET: ${NANDU_JWT_SECRET}
      # Root user configuration
      NANDU_ROOT_USER: ${NANDU_ROOT_USER}
      NANDU_ROOT_PASSWD: ${NANDU_ROOT_PASSWD}
      NANDU_ROOT_EMAIL: ${NANDU_ROOT_EMAIL}
      # Storage configuration
      NANDU_LOCAL_STORAGE_DIR: /app/storage/packages
      # Log configuration
      NANDU_LOG_LEVEL: ${NANDU_LOG_LEVEL:-info}
      # Dashboard URL 
      NANDU_DASHBOARD_URL: ${NANDU_DASHBOARD_URL:-http://localhost:4567}
      # Email configuration
      NANDU_EMAIL_FROM: ${NANDU_EMAIL_FROM}
      NANDU_EMAIL_USE_TRANSPORT: ${NANDU_EMAIL_USE_TRANSPORT}
      NANDU_EMAIL_SMTP_HOST: ${NANDU_EMAIL_SMTP_HOST}
      NANDU_EMAIL_SMTP_PORT: ${NANDU_EMAIL_SMTP_PORT}
      NANDU_EMAIL_SMTP_USER: ${NANDU_EMAIL_SMTP_USER}
      NANDU_EMAIL_SMTP_PASS: ${NANDU_EMAIL_SMTP_PASS}
    volumes:
      - nandu-storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/-/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nandu}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nandu}
      POSTGRES_DB: ${POSTGRES_DB:-nandu}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nandu}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nandu-storage:
  postgres-data:
