export enum OrganizationAction {
  billing,
  addMember,
  removeMember,
  listMembers,
  renameOrg,
  deleteOrg,
  changeMemberRole,
  createTeam,
  listTeams,
  listTeamMembers,
  deleteTeam,
  addMemberToTeam,
  removeMemberFromTeam,
  manageTeamPackageAccess,
  publishPackage,
}
