name: Docker Build and Publish

on:
  # Build but don't publish on PRs (validation only)
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'packages/**'
      - '.github/workflows/docker.yml'
  
  # Build and publish on push to main
  push:
    branches: [main]
  
  # Build and publish on releases
  release:
    types: [published]
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to GitHub Container Registry'
        type: boolean
        default: false

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed for publishing to GHCR
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
      
      # Determine if we should publish
      - name: Set publishing flag
        id: publish
        run: |
          # Publish if:
          # 1. Push to main branch
          # 2. Release is published
          # 3. Manual workflow run with publish=true
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] || \
             [[ "${{ github.event_name }}" == "release" ]] || \
             [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.publish }}" == "true" ]]; then
            echo "should_publish=true" >> $GITHUB_OUTPUT
          else
            echo "should_publish=false" >> $GITHUB_OUTPUT
          fi
      
      # Only login if we're going to publish
      - name: Log in to GitHub Container Registry
        if: steps.publish.outputs.should_publish == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.publish.outputs.should_publish }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.ref_name }}
      
      # Summarize what we did
      - name: Workflow summary
        run: |
          echo "## Docker Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Event:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Ref:** ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Images Built:**" >> $GITHUB_STEP_SUMMARY
          
          # List all the tags we built
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
            echo "  - \`$tag\`" >> $GITHUB_STEP_SUMMARY
          done
          
          echo "" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ steps.publish.outputs.should_publish }}" == "true" ]]; then
            echo "✅ **Published to GitHub Container Registry**" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ **Build only (not published)**" >> $GITHUB_STEP_SUMMARY
          fi
